# Generated by Django 3.2.6 on 2021-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.BigIntegerField()),
                ('device_address', models.CharField(max_length=50)),
                ('c02', models.FloatField()),
                ('tv02', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('read_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
